-- Migration 001: Core schema (MSSQL → PostgreSQL)
-- Run: psql -h localhost -U pnl -d punjabnewsline -f migration/001_schema.sql

CREATE TABLE IF NOT EXISTS ox_article (
  article_code    INTEGER PRIMARY KEY,
  date            TIMESTAMPTZ,
  cgry_code       SMALLINT,
  sgmt_code       SMALLINT,
  article_head    TEXT,
  article_desc    TEXT,
  article_body    TEXT,
  article_sub     TEXT,
  meta_title      TEXT,
  meta_desc       TEXT,
  meta_keys       TEXT,
  permalink       TEXT,
  tag1            TEXT,
  tag2            TEXT,
  tag3            TEXT,
  reporter        TEXT,
  reflink         TEXT,
  lang_code       SMALLINT,
  team_code       SMALLINT,
  subc_code       SMALLINT,
  user_code       SMALLINT,
  photo_caption   TEXT,
  subhead         TEXT,
  cgry_list       TEXT,
  group_list      TEXT,
  progress        BOOLEAN,
  hits            NUMERIC DEFAULT 0,
  active          SMALLINT DEFAULT 0,
  days            SMALLINT,
  ex_date         TIMESTAMPTZ,
  cap_all         TEXT,
  article_sub2    TEXT,
  article_sub3    TEXT,
  vlink           TEXT,
  mode_code       SMALLINT
);

CREATE INDEX IF NOT EXISTS idx_article_permalink ON ox_article(permalink);
CREATE INDEX IF NOT EXISTS idx_article_active_date ON ox_article(active, date DESC);
CREATE INDEX IF NOT EXISTS idx_article_cgry ON ox_article(cgry_code, active);
CREATE INDEX IF NOT EXISTS idx_article_lang ON ox_article(lang_code, active);
CREATE INDEX IF NOT EXISTS idx_article_search ON ox_article USING gin(to_tsvector('simple', coalesce(article_head,'') || ' ' || coalesce(article_body,'')));

CREATE TABLE IF NOT EXISTS ox_video (
  video_code      INTEGER PRIMARY KEY,
  date            TIMESTAMPTZ,
  cgry_code       SMALLINT,
  video_head      TEXT,
  video_desc      TEXT,
  permalink       TEXT,
  vlink           TEXT,
  active          SMALLINT DEFAULT 0,
  hits            NUMERIC DEFAULT 0,
  meta_title      TEXT,
  meta_desc       TEXT,
  meta_keys       TEXT,
  lang_code       SMALLINT
);

CREATE INDEX IF NOT EXISTS idx_video_permalink ON ox_video(permalink);
CREATE INDEX IF NOT EXISTS idx_video_active ON ox_video(active, date DESC);

CREATE TABLE IF NOT EXISTS ox_gallery (
  gallery_code    INTEGER PRIMARY KEY,
  date            TIMESTAMPTZ,
  cgry_code       SMALLINT,
  gallery_head    TEXT,
  gallery_desc    TEXT,
  permalink       TEXT,
  active          SMALLINT DEFAULT 0,
  hits            NUMERIC DEFAULT 0,
  meta_title      TEXT,
  meta_desc       TEXT,
  meta_keys       TEXT,
  lang_code       SMALLINT
);

CREATE INDEX IF NOT EXISTS idx_gallery_permalink ON ox_gallery(permalink);

CREATE TABLE IF NOT EXISTS ox_poll (
  poll_code       INTEGER PRIMARY KEY,
  date            TIMESTAMPTZ,
  poll_question   TEXT,
  permalink       TEXT,
  active          SMALLINT DEFAULT 0,
  lang_code       SMALLINT
);

CREATE TABLE IF NOT EXISTS ox_poll_option (
  option_code     INTEGER PRIMARY KEY,
  poll_code       INTEGER REFERENCES ox_poll(poll_code),
  option_text     TEXT,
  votes           INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_poll_permalink ON ox_poll(permalink);

CREATE TABLE IF NOT EXISTS ox_code (
  cgry_code       INTEGER PRIMARY KEY,
  cgry_name       TEXT,
  cgry_url        TEXT,
  cgry_order      SMALLINT,
  parent_code     SMALLINT DEFAULT 0,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_team (
  team_code       INTEGER PRIMARY KEY,
  team_name       TEXT,
  team_desc       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_comment (
  comment_code    SERIAL PRIMARY KEY,
  article_code    INTEGER REFERENCES ox_article(article_code),
  comment_text    TEXT,
  name            TEXT,
  email           TEXT,
  date            TIMESTAMPTZ DEFAULT NOW(),
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_member (
  member_code     INTEGER PRIMARY KEY,
  username        TEXT UNIQUE,
  password_hash   TEXT,
  email           TEXT,
  role            TEXT DEFAULT 'reporter',
  active          SMALLINT DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ox_advt (
  advt_code       INTEGER PRIMARY KEY,
  advt_head       TEXT,
  permalink       TEXT,
  advt_body       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_classified (
  classified_code INTEGER PRIMARY KEY,
  company_name    TEXT,
  permalink       TEXT,
  classified_desc TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_file (
  file_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMPTZ,
  file_name       TEXT,
  file_desc       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_feedback (
  feed_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMPTZ,
  feed_name       TEXT,
  feed_phone      TEXT,
  feed_email      TEXT,
  feed_desc       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_profile (
  prof_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMPTZ,
  prof_head       TEXT,
  prof_desc       TEXT,
  prof_file       TEXT,
  meta_title      TEXT,
  meta_desc       TEXT,
  meta_keys       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_pollx (
  pllx_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMPTZ,
  pllx_head       TEXT,
  poll1           TEXT,
  poll2           TEXT,
  poll3           TEXT,
  poll4           TEXT,
  poll5           TEXT,
  poll6           TEXT,
  count1          INTEGER DEFAULT 0,
  count2          INTEGER DEFAULT 0,
  count3          INTEGER DEFAULT 0,
  count4          INTEGER DEFAULT 0,
  count5          INTEGER DEFAULT 0,
  count6          INTEGER DEFAULT 0,
  active          SMALLINT DEFAULT 0,
  lang_code       SMALLINT,
  meta_title      TEXT,
  meta_desc       TEXT,
  meta_keys       TEXT,
  permalink       TEXT
);

CREATE INDEX IF NOT EXISTS idx_pollx_active ON ox_pollx(active, pllx_code DESC);
CREATE INDEX IF NOT EXISTS idx_pollx_permalink ON ox_pollx(permalink);

CREATE TABLE IF NOT EXISTS ox_multiphoto (
  multi_code      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  photo_code      INTEGER REFERENCES ox_gallery(gallery_code),
  file_name       TEXT,
  photo_caption   TEXT,
  sorting         INTEGER,
  active          SMALLINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_multiphoto_photo ON ox_multiphoto(photo_code, active);

CREATE TABLE IF NOT EXISTS ox_response (
  resp_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMPTZ,
  resp_name       TEXT,
  resp_phone      TEXT,
  resp_email      TEXT,
  resp_desc       TEXT,
  resp_head       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_submit (
  submit_code     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMPTZ,
  submit_name     TEXT,
  submit_phone    TEXT,
  submit_email    TEXT,
  submit_desc     TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_user (
  user_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name       TEXT,
  user_login      TEXT,
  user_pwd        TEXT,
  right_list      TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_user_login ON ox_user(user_login, active);

CREATE TABLE IF NOT EXISTS ox_right (
  right_code      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  right_name      TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_title (
  titl_code       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titl_name       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_acategory (
  acgr_code       INTEGER PRIMARY KEY,
  acgr_name       TEXT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_ccategory (
  ccgr_code       INTEGER PRIMARY KEY,
  ccgr_name       TEXT,
  sgmt_code       SMALLINT,
  active          SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ox_counter (
  code            INTEGER PRIMARY KEY,
  counter         NUMERIC DEFAULT 0
);

-- Unique constraint on permalinks to catch duplicates
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_article_permalink') THEN
    ALTER TABLE ox_article ADD CONSTRAINT uq_article_permalink UNIQUE (permalink);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_video_permalink') THEN
    ALTER TABLE ox_video ADD CONSTRAINT uq_video_permalink UNIQUE (permalink);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_gallery_permalink') THEN
    ALTER TABLE ox_gallery ADD CONSTRAINT uq_gallery_permalink UNIQUE (permalink);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_poll_permalink') THEN
    ALTER TABLE ox_poll ADD CONSTRAINT uq_poll_permalink UNIQUE (permalink);
  END IF;
END $$;

-- Legacy compatibility views used by old ASP.NET queries.
-- These preserve legacy object names while routing reads to migrated base tables.
CREATE OR REPLACE VIEW ox_articlev AS SELECT * FROM ox_article;
CREATE OR REPLACE VIEW ox_videov AS SELECT * FROM ox_video;
CREATE OR REPLACE VIEW ox_galleryv AS SELECT * FROM ox_gallery;
CREATE OR REPLACE VIEW ox_commentv AS SELECT * FROM ox_comment;
CREATE OR REPLACE VIEW ox_teamv AS SELECT * FROM ox_team;
CREATE OR REPLACE VIEW ox_advtv AS SELECT * FROM ox_advt;
CREATE OR REPLACE VIEW ox_galleryr AS SELECT * FROM ox_gallery;
